PRODUCTION_INFO:
     - PURPOSE: download
       NAME: PINX
       HOST: 192.168.1.3
       USERNAME: skns
       PASSWORD: hyperns1234!
       PORT: 22
       LOCAL_PATH: C:\Users\skns\temp
       FILES_INFO:
            - TYPE: mariadb
              FILENAME_FORMAT: general.log-20210120.gz
              DIR_PATH: /svc/log/mariadb/archive
            - TYPE: appweb
              FILENAME_FORMAT: appweb.out-20210120.gz
              DIR_PATH: /svc/log/was
            - TYPE: appadmin
              FILENAME_FORMAT: appadmin.out-20210120.gz
              DIR_PATH: /svc/log/was
            - TYPE: accesslog
              FILENAME_FORMAT: www_access_log.2021-01-20.log
              DIR_PATH: /svc/log/was/appweb/accesslogs

     - PURPOSE: upload
       HOST: 172.27.12.21
       USERNAME: skns
       PASSWORD: hyperns!
       PORT: 22
       LOCAL_PATH: C:\Users\skns\temp
       REMOTE_PATH: /home/skns/raw_local/data/PINX

#     - PURPOSE: upload
#       HOST: 172.27.12.39
#       USERNAME: skns
#       PASSWORD: 1q2w#E$R
#       PORT: 22
#       LOCAL_PATH: C:\\Users\\skns\\temp
#       REMOTE_PATH: /home/skns/raw_local/data
#
#     - PURPOSE: upload_to_hdfs
#       HOST: 172.27.12.21
#       USERNAME: skns
#       PASSWORD: hyperns!
#       PORT: 22
#       LOCAL_PATH: C:\\Users\\skns\\temp
#       REMOTE_PATH: /home/skns/raw_local/data
#       SHELL_COMMAND: sh /home/skns/raw_local/scripts/execute_upload.sh {REMOTE_PATH} {MISSING_DATE_STRING}